name: aom

on: [push, pull_request]

jobs:

  linux-tests:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install aom
      run: |
        sudo apt-get install libaom-dev

    - name: Run tests
      run: |
        cargo test --all-features --verbose

    - name: Build docs
      run: |
        cargo doc --all-features --verbose

  windows-tests-gnu:

    runs-on: windows-latest

    env:
      MSYSTEM: MINGW64
      MSYS2_PATH_TYPE: inherit

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Windows gnu
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable-gnu

    - name: Install msys2 packages
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-pkgconf mingw-w64-x86_64-aom
        update: true

    - name: Run tests
      shell: msys2 {0}
      run: |
        cargo test --all-features --verbose
